apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80         # The port that the service will expose
      targetPort: 4499 # The port on the container that the service will forward traffic to
  type: LoadBalancer  # Use LoadBalancer to expose the service externally