apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow-container
        image: khuntia1234/wisecow:v27
        ports:
        - containerPort: 4499
        env:
        - name: DEBIAN_FRONTEND
          value: "noninteractive"
