name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            khuntia1234/wisecow:v${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes config
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Transfer Kubernetes manifests to EC2
        uses: appleboy/scp-action@vmaster
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "wisecow.yaml,wisecow-srv.yaml"
          target: "/home/ubuntu/wisecow/"

      - name: SSH into AWS EC2 and apply Kubernetes manifests
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/wisecow/
            sed -i "s|khuntia1234/wisecow:.*|khuntia1234/wisecow:v${{ github.run_number }}|g" wisecow.yaml
            kubectl apply -f wisecow-srv.yaml --insecure-skip-tls-verify --validate=false
            kubectl apply -f wisecow.yaml --insecure-skip-tls-verify --validate=false
